# Generated by Django 3.0 on 2025-03-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'house', 'verbose_name_plural': 'house'},
        ),
        migrations.AlterModelTable(
            name='house',
            table='house',
        ),
    ]
